server:
  port: 8888
  
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://WonSik36@bitbucket.org/WonSik36/cloud-config.git
          username: WonSik36
          password: dkap10flzk27!
          skip-ssl-validation: true